- name: 00096_jerseyshort
  gender: male
- name: 00096_longshort
  gender: male
- name: 00096_shirtlong
  gender: male
- name: 00096_shirtshort
  gender: male
- name: 00096_shortlong
  gender: male
- name: 00096_shortshort
  gender: male
- name: 00215_jerseyshort
  gender: male
- name: 00215_longshort
  gender: male
- name: 00215_poloshort
  gender: male
- name: 00215_shortlong
  gender: male
- name: 03375_blazerlong
  gender: male
- name: 03375_longlong
  gender: male
- name: 03375_shortlong
  gender: male
- name: 03375_shortshort
  gender: male
