expname: resynth_pretrained
result_folder: results
device: 'cuda'

smpl_model_path: smpl_models
data_scans_path: data_scans
data_templates_path: data_templates

num_joints: 24 # doesn't support other values yet
leg_angle: 15.0
n_cano_points: 50000
