- dirc: rightfront
  y_rot: 45
  x_rot: 30
  y_shift: 0.25
  x_stretch: 1.25
- dirc: rightback
  y_rot: 135
  x_rot: -30
  y_shift: 0.25
  x_stretch: 1.25
- dirc: leftback
  y_rot: 225
  x_rot: 30
  y_shift: 0.25
  x_stretch: 1.25
- dirc: leftfront
  y_rot: 315
  x_rot: -30
  y_shift: 0.25
  x_stretch: 1.25