- name: rp_anna_posed_001
  gender: female
- name: rp_beatrice_posed_025
  gender: female
- name: rp_christine_posed_027
  gender: female
- name: rp_celina_posed_005
  gender: female
- name: rp_alexandra_posed_006
  gender: female
- name: rp_carla_posed_006
  gender: female
- name: rp_cindy_posed_005
  gender: female
- name: rp_corey_posed_006
  gender: male
- name: rp_eric_posed_006
  gender: male
- name: rp_carla_posed_004
  gender: female
- name: rp_eric_posed_035
  gender: male
- name: rp_felice_posed_004
  gender: female
